# Generated by Django 6.0.2 on 2026-02-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0019_historicaljobtitle_is_canonical_jobtitle_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePermission',
        ),
    ]
